name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node - version }}