name: Linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm install

      - name: Building app
        run: npm run build:prod
        if: always()

      - name: Linting ts
        run: npm run lint:ts
        if: always()

      - name: Linting scss
        run: npm run lint:scss
        if: always()

      - name: Testing ts
        run: npm run test:unit
        if: always()

